### ISSUE TITLE
asdw | wc

### ISSUE THREAD

**Issue by Daniyel03** [mtelek/minishell#4]

**Comment by Daniyel03** [comment]
more original behaviour:
execute from right to left, wc gets executed, waits for input from cmd1, cmd1 doesnt exist, no output and wc will also close with 0 0 0 when its input fd got closed.

current behaviour: 
cmd1 nonexisting errormessage gets pipes as input to wc

![image](https://github.com/user-attachments/assets/f871e9b1-3cd6-4d72-9afd-1f0b5d773ab1)

**Comment by Daniyel03** [comment]
by adding this behaviour, the case

-  cat /dev/urandom | head -n 5 

will also work properly.

**Comment by mtelek** [comment]
now it works, exept yes | head -n
