### ISSUE TITLE
30.08

### ISSUE THREAD

**Issue by Daniyel03** [mtelek/minishell#7]
ls | wc > out, still open fd

g | ls, wrong errorcode, just take exitcode from last cmd 

exit definetely problematic:

![image](https://github.com/user-attachments/assets/b77fec9f-72cb-468c-ac4a-e5afd51c4b29)

definetely lost memory leaks when multiple heredocs

add ? as var delimiter in expander:

![image](https://github.com/user-attachments/assets/f4311729-90cf-48ac-8d3c-26a6c79d34f0)

**Comment by mtelek** [comment]
fixed exit and builtins now working
